GdzieJacht_Web/Controllers/FriendsController.cs
using GdzieJacht_Web.GdzieJachtService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GdzieJacht_Web.Models;

namespace GdzieJacht_Web.Controllers
{
    [Authorize]
    public class FriendsController : Controller
    {
        private User loggedUser;
        private IGdzieJachtService gdzieJachServiceClient;
        private AuthenticationInfo ai = new AuthenticationInfo { Username = "test", Password = "test" };

        public FriendsController(IGdzieJachtService gdzieJachServiceClient)
        {
            this.gdzieJachServiceClient = gdzieJachServiceClient;
            loggedUser = (User)System.Web.HttpContext.Current.Session["User"];
        }

        public ActionResult Friends()
        {
            if (loggedUser == null)
                return Redirect(Url.Action("Logout", "Account", new { id = "SessionExpired" }));
            return View();
        }

        public ActionResult AddFriend(int friendID)
        {
            if (loggedUser == null)
                return JavaScript("onFailure();");
            gdzieJachServiceClient.AddFriend(loggedUser.user_id, friendID, ai);
            return View("GetFriends", gdzieJachServiceClient.GetFriends(loggedUser.user_id, ai));
        }

        public ActionResult RemoveFriend(int friendID)
        {
            if (loggedUser == null)
                return JavaScript("onFailure();");
            gdzieJachServiceClient.RemoveFriend(loggedUser.user_id, friendID, ai);
            return View("GetFriends", gdzieJachServiceClient.GetFriends(loggedUser.user_id, ai));
        }

        public ActionResult SearchFriends(string userName)
        {
            if (loggedUser == null)
                return JavaScript("onFailure();");
            IEnumerable<User> result = null;
            if (!string.IsNullOrEmpty(userName))
            {
                IEnumerable<int> friendsIDs = from user in gdzieJachServiceClient.GetFriends(loggedUser.user_id, ai)
                                              select user.user_id;
                result = from user in gdzieJachServiceClient.GetUsersList(ai).Where(u => !friendsIDs.Contains(u.user_id) && u.user_id != loggedUser.user_id)
                         orderby user.user_name
                         where user.user_name.ToLower().Contains(userName.ToLower())
                         select user;
                ViewBag.UserName = userName;
            }
            return PartialView(result);
        }

        public ActionResult GetFriends()
        {
            if (loggedUser == null)
                return JavaScript("onFailure();");
            return PartialView(gdzieJachServiceClient.GetFriends(loggedUser.user_id, ai));
        }
    }
}

GdzieJacht_Web/Controllers/PhotoController.cs
using GdzieJacht_Web.GdzieJachtService;
using GdzieJacht_Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;

namespace GdzieJacht_Web.Controllers
{
    [Authorize]
    public class PhotoController : Controller
    {
        private User loggedUser;
        private IGdzieJachtService gdzieJachtServiceClient;
        private AuthenticationInfo ai = new AuthenticationInfo { Username = "test", Password = "test" };
        private Photo[] photos;

        public PhotoController(IGdzieJachtService gdzieJachtServiceClient)
        {
            this.gdzieJachtServiceClient = gdzieJachtServiceClient;
            loggedUser = (User)System.Web.HttpContext.Current.Session["User"];
        }

        public ActionResult Friends_To_Choose()
        {
            if (loggedUser != null)
            {
                ViewBag.LoggedUserName = loggedUser.user_name;
                ViewBag.LoggedUserID = loggedUser.user_id;
                ViewBag.Error = "";
                string message1 = "Nie dodałeś jeszcze znajomych";
                string message2 = "Żaden z Twoich znajomych nie ma zdjęć";

                List<User> users_with_photos = new List<User>();
                User[] users;

                try
                {
                    users = gdzieJachtServiceClient.GetFriends(loggedUser.user_id, ai);

                    if (users.Count() != 0 && users != null)
                    {
                        for (int i = 0; i < users.Count(); i++)
                        {   
                            if (gdzieJachtServiceClient.GetUserPhotoCount(users[i].user_id, ai)!=0)
                            {
                                users_with_photos.Add(users[i]);
                            }
                        }

                        if (users_with_photos.Count == 0 || users_with_photos == null)
                        {
                            throw new Exception(message2);
                        }
                    }
                    else
                    {
                        throw new Exception(message1);
                    }
                }
                catch (Exception e)
                {
                    ExceptionDetail exdetail = new ExceptionDetail(e);
                    FaultException<ExceptionDetail> exception = new FaultException<ExceptionDetail>(exdetail);
                    //var except = e as FaultException<ExceptionDetail>;
                    //var exceptiondetail = except.Detail.Type;
                    if (exdetail.Type == "GdzieJachtService.CustomException")
                    {
                        ViewBag.Error = "Nie dodałeś jeszcze znajomych lub Twoi znajomi nie mają zdjęć.";
                    }
                    ViewBag.Error = e.Message;
                }

                return PartialView(users_with_photos);
            }
            else
            {
                //return Redirect("~/Account/Account");
                return Redirect(Url.Action("Logout", "Account", new { id = "SessionExpired" }));
            }
        }

        public ActionResult Friends_Gallery(int? friend_id, int page=1)
        {
            if (loggedUser != null)
            {
                ViewBag.ErrorGallery = "";
                string message = "Brak zdjęć użytkownika";
                int count_total;
                int count;

                List<Photo> photo_list = new List<Photo>();
                try
                {
                    count = gdzieJachtServiceClient.GetUserPhotoCount((int)friend_id, ai);
                    count_total = (int)Math.Ceiling((decimal)count / 10);

                    if (count>=10)
                    {
                        for (int i = 0; i <= count_total+1; i++)
                        {
                            photos = gdzieJachtServiceClient.Get10UserPhotos((int)friend_id, i, ai);

                            for (int j = 0; j < photos.Count(); j++)
                            {
                                if (photos[j] != null)
                                {
                                    photo_list.Add(photos[j]);
                                }
                            }
                        }
                    }

                    else
                    {
                        photo_list = gdzieJachtServiceClient.GetUserPhotos((int)friend_id, ai).ToList();
                    }

                    if (photo_list.Count != 0)
                    {
                        PhotoViewModel viewModel = new PhotoViewModel
                        {
                            Photos = photo_list,
                            //.OrderBy(p => p.photo_id)
                            //.Skip((page - 1) * pageSize)
                            //.Take(pageSize),
                            PagingInfo = new PagingInfo
                            {
                                CurrentPage = page,
                                ItemsPerPage = 10,
                                TotalItems = count_total
                            }
                        };

                        return PartialView(viewModel); 
                       
                    }
                    else
                    {
                        throw new Exception(message);
                    }
                }

                catch (Exception e)
                {
                    ExceptionDetail exdetail = new ExceptionDetail(e);
                    FaultException<ExceptionDetail> exception = new FaultException<ExceptionDetail>(exdetail);
                    //var except = e as FaultException<ExceptionDetail>;
                    //var exceptiondetail = except.Detail.Type;
                    if (exdetail.Type == "GdzieJachtService.CustomException")
                    {
                        ViewBag.ErrorGallery = e.Message;
                    }
                    ViewBag.ErrorGallery = e.Message;
                    return PartialView();
                }
            }
            else
            {
                //return Redirect("~/Account/Account");
                return JavaScript("onFailure();");
            }
        }

        public ActionResult Photo()
        {
            if (loggedUser != null)
            {
                return View();
            }
            else
            {
                //return Redirect("~/Account/Account");
                return Redirect(Url.Action("Logout", "Account", new { id = "SessionExpired" }));
            }

        }

    }
}

GdzieJacht_Web/Controllers/TripController.cs
using GdzieJacht_Web.GdzieJachtService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;

namespace GdzieJacht_Web.Controllers
{
    public class TripController : Controller
    {
        private GdzieJachtServiceClient client;
        private Trip trip;
        private AuthenticationInfo info;
        private User loggedUser;

        public TripController(GdzieJachtServiceClient client, Trip trip, AuthenticationInfo info)
        {
            this.client = client;
            this.trip = trip;
            this.info = info;
            loggedUser = (User)System.Web.HttpContext.Current.Session["User"];
        }

        public ViewResult Trip()
        {
            return View(new List<Trip> {trip});
        }

        public ActionResult GetTrip(Int32 id)
        {
            //TODO: Dodać weryfikację czy trasa należy do użytkownika
            if (loggedUser != null)
            {
                Trip trip = null;
                try
                {

                    trip = client.GetTrip(id, this.info);
                }
                catch (FaultException ex)
                {
                    return HttpNotFound();
                }

                return View(trip);
            }
            else
            {
                return Redirect(Url.Action("Logout", "Account", new { id = "SessionExpired" }));
            }
        }

        public PartialViewResult GetCheckpoints(Int32 id)
        {
            var auth = new AuthenticationInfo
            {
                Username = "test",
                Password = "test"
            };

            var trip = client.GetTrip(id, auth);

            var checkpoints = client.GetTripCheckpoints(trip, auth);

            return PartialView(checkpoints);
        }

        //testowa metoda przejścia do widoku Trip
        //wykorzystywana w widoku, z ktorego chcemy przejść do Trip, np w Loginie
        public ActionResult MoveToTrip()
        {
            if (loggedUser != null)
            {
                var auth = new AuthenticationInfo
                {
                    Username = "test",
                    Password = "test"
                };
                var trips = client.GetTripListForUser(loggedUser.user_id, auth);
                if (trips == null || !trips.Any())
                    return View("~/Views/Trip/NoTrips.cshtml");

                var userLanguage = System.Globalization.CultureInfo.CurrentUICulture;
                // return View("~/Views/Trip/Trip.cshtml", trips.OrderByDescending(c => c.trip_date.ToString().ToString(userLanguage)).ToList());
                return View("~/Views/Trip/Trip.cshtml", trips.OrderByDescending(c => c.trip_date.ToString().ToString(System.Globalization.CultureInfo.InvariantCulture)).ToList());
            }
            else
            {
                return Redirect(Url.Action("Logout", "Account", new { id = "SessionExpired" }));
            }
        }

        //reszta kodu
        public ActionResult GetPoints(Int32 id)
        {
            var auth = new AuthenticationInfo
            {
                Username = "test",
                Password = "test"
            };

            var trip = id == 0 ? new Trip() : client.GetTrip(id, auth);

            var checkpoints = client.GetTripCheckpoints(trip, auth);

          
            return Json(checkpoints, JsonRequestBehavior.AllowGet);
        }
    }
}

GdzieJacht_Web/Controllers/UserProfileController.cs
using GdzieJacht_Web.GdzieJachtService;
using GdzieJacht_Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GdzieJacht_Web.Controllers
{
    [Authorize]
    public class UserProfileController : Controller
    {

        private IGdzieJachtService gdzieJachServiceClient;

        private AuthenticationInfo ai = new AuthenticationInfo { Username = "test", Password = "test" };

        private User loggedUser;
        
        public UserProfileController(IGdzieJachtService gdzieJachServiceClient)
        {
            this.gdzieJachServiceClient = gdzieJachServiceClient;
            this.ai = new AuthenticationInfo { Username = "test", Password = "test" };
            this.loggedUser = (User)System.Web.HttpContext.Current.Session["User"];
        }

        public ActionResult UserProfile()
        {
            if (loggedUser != null)
            {
                UserAndPhotoViewModel userAndPhotoViewModel = new UserAndPhotoViewModel();
                userAndPhotoViewModel.user = loggedUser;
                userAndPhotoViewModel.userPhoto = retrieveRandomUserPhoto();
                return View(userAndPhotoViewModel);
            }
            else
            {
                return Redirect(Url.Action("Logout", "Account", new { id = "SessionExpired" }));
            }
        }

        public ActionResult MoveToWebUserProfile()
        {
            if (loggedUser != null)
                return View("~/Views/UserProfile/UserProfile.cshtml");
            else
                return Redirect(Url.Action("Logout", "Account", new { id = "SessionExpired" }));
        }

        private Photo retrieveRandomUserPhoto()
        {
            Photo userPhoto = null;
            try
            {
                Photo[] userPhotos = gdzieJachServiceClient.GetUserPhotos(loggedUser.user_id, ai);
                if (userPhotos.Length > 0)
                {
                    Random random = new Random();
                    userPhoto = userPhotos[random.Next(userPhotos.Length)];
                }
            }
            catch (Exception ignored) {}
           
            return userPhoto;
        }
    }
}

GdzieJacht_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    @* <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" type="text/css" />*@
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://lipis.github.io/bootstrap-social/bootstrap-social.css">
    <link rel="stylesheet" href="http://lipis.github.io/bootstrap-social/assets/css/font-awesome.css">
  @*  <link href="@Url.Content("~/Content/font-awesome.css")" rel="stylesheet" type="text/css" />*@
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="~/Scripts/jquery-1.8.0.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-color navbar-inverse navbar-fixed-top" role="navigation" style="border-color:transparent">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="/Trip/MoveToTrip">
                        <img src="~/Content/images/poziome_biale.png" height="40px" /></a>

                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            @Html.ActionLink("PODRÓŻ", "MoveToTrip", "Trip")
                        </li>
                        <li>
                            @Html.ActionLink("GALERIA", "Photo", "Photo")
                        </li>
                        <li>
                            @Html.ActionLink("ZNAJOMI", "Friends", "Friends")
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
                 
            </div>
            <!-- /.container -->
            <div id="loginsection">
                <div class="container">
                    <div id="loginsectionuser">
                         @using (Html.BeginForm("Logout", "Account"))
                    {
                        GdzieJacht_Web.GdzieJachtService.User loggedUser = (GdzieJacht_Web.GdzieJachtService.User)HttpContext.Current.Session["User"];
                        //przycisk, który służy do wylogowania
                         <span class="form-group">
                             @Html.ActionLink(@loggedUser.user_name, "UserProfile", "UserProfile")
                             <input type="submit" value="wyloguj" style="background-color:transparent; border:none" />
                         </span>
                    }     
                    </div>                    
                </div>
           
        </div>
        </nav>
       
    </header>
    <div class="container">
        <div id="page-wrapper">
            @RenderBody()
        </div>
        <!-- /#page-wrapper -->
    </div>
    <footer>
        <div class="container">
            <div class="copyright-section">
                <div class="row">
                    <div class="col-md-6">
                        <p>&copy; 2015 Gdzie mój jacht -  All Rights Reserved </p>
                    </div>
                    <!-- .col-md-6 -->
                    <div class="col-md-6">
                        <ul class="footer-nav">
                            <li>
                                 Informatyka, magisterskie 2014/15 
                            </li>
                            <li>
                                WEB TEAM
                            </li>
                        </ul>
                    </div>
                    <!-- .col-md-6 -->
                </div>
                <!-- .row -->
            </div>
        </div>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.5.3.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.metisMenu.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/my.js")" type="text/javascript"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>